### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by jessp01** [mkoppanen/php-aware#5]
Hello @DrHayt, @mkoppanen 

As I was about to start a similar project, I came across yours.
Since it was well written and was a good starting point, I've made a pull request that fixes the code so that it compiles on PHP > 5.3 and also fixed a segfault and implemented an elasticsearch backend.

I see the last push to this repo was done in 2011 so I am wondering whether or not you still have an active interest in the project? if so, I'd be happy to continue work on it with you, if not, I'll just fork it over and continue on my own, while, of course, keeping the credit for the work @DrHayt has done intact.

Please let me know.

Thanks,

**Comment by mkoppanen** [comment]
Hey,

I think I wrote this extension ages ago because APM extension did not support pluggable backends. The extension didn't pick up much interest and nowadays I don't work with php anymore.

I am more than happy for anyone to take over the development of this extension.

**Comment by jessp01** [comment]
Thanks @mkoppanen, I'll continue with it from my own repo then, keeping credit where credit is due of course:)
If you are ever interested in rejoining, I will be happy to have you.
